obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[-0.105,-0.105],[-0.105,0.105], [0.041,0.105], [0.041,-0.105]]
inflation_radius: 0.5
cost_scaling_factor: 3.0
observation_sources: scan
scan: {sensor_frame: chassis, observation_persistence: 0.0, 
max_obstacle_height: 0.4, min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}